#!/bin/sh
set -euo pipefail

if [[ ! -f "${CONF_PATH}/config.yaml" ]]; then
	./gateway setup --config-dir "${CONF_PATH}"
fi

RUN_PARAMS="${RUN_PARAMS:-} --config-dir ${CONF_PATH}"

exec ./gateway run $RUN_PARAMS "$@"
