// Code generated by storj.io/gateway/cmd/apierrgen. DO NOT EDIT.

package apierr

import "net/http"

const (
	CodeNone Code = iota
	CodeAccessDenied
	CodeAuthorizationHeaderMalformed
	CodeBadDigest
	CodeChecksumMismatch
	CodeContentLengthWithTransferEncoding
	CodeContentMD5Mismatch
	CodeContentSHA256Mismatch
	CodeEntityTooLarge
	CodeEntityTooSmall
	CodeExpiredPresignedRequest
	CodeInternal
	CodeInvalidAccessKeyID
	CodeInvalidContentMD5
	CodeInvalidContentSHA256
	CodeInvalidForceDelete
	CodeInvalidRequest
	CodeMalformedDate
	CodeMalformedExpires
	CodeMalformedPOSTDate
	CodeMalformedPOSTRequest
	CodeMalformedPresignedDate
	CodeMalformedXML
	CodeMaximumExpires
	CodeMissingContentLength
	CodeMissingPOSTPolicy
	CodeMissingSecurityHeader
	CodeNegativeExpires
	CodeNoSuchCORSConfiguration
	CodeNoSuchWebsiteConfiguration
	CodeNotImplemented
	CodeRequestNotReadyYet
	CodeRequestTimeTooSkewed
	CodeSignatureDoesNotMatch
	CodeUnsupportedECDSAP256SHA256
	CodeUnsupportedSignature
)

var codeToResponse = map[Code]Response{
	CodeAccessDenied: {
		Code:           "AccessDenied",
		Description:    "Access Denied",
		HTTPStatusCode: http.StatusForbidden,
	},
	CodeAuthorizationHeaderMalformed: {
		Code:           "AuthorizationHeaderMalformed",
		Description:    "The authorization header that you provided is not valid.",
		HTTPStatusCode: http.StatusBadRequest,
	},
	CodeBadDigest: {
		Code:           "BadDigest",
		Description:    "The Content-MD5 or checksum value you specified did not match what we received.",
		HTTPStatusCode: http.StatusBadRequest,
	},
	CodeChecksumMismatch: {
		Code:           "BadDigest",
		Description:    "The checksum value you specified did not match what we received.",
		HTTPStatusCode: http.StatusBadRequest,
	},
	CodeContentLengthWithTransferEncoding: {
		Code:           "InvalidRequest",
		Description:    "Cannot specify both Content-Length and Transfer-Encoding HTTP headers.",
		HTTPStatusCode: http.StatusBadRequest,
	},
	CodeContentMD5Mismatch: {
		Code:           "BadDigest",
		Description:    "",
		HTTPStatusCode: http.StatusBadRequest,
	},
	CodeContentSHA256Mismatch: {
		Code:           "XAmzContentSHA256Mismatch",
		Description:    "The provided 'x-amz-content-sha256' header does not match what was computed.",
		HTTPStatusCode: http.StatusBadRequest,
	},
	CodeEntityTooLarge: {
		Code:           "EntityTooLarge",
		Description:    "Your proposed upload exceeds the maximum allowed object size.",
		HTTPStatusCode: http.StatusBadRequest,
	},
	CodeEntityTooSmall: {
		Code:           "EntityTooSmall",
		Description:    "Your proposed upload is smaller than the minimum allowed object size.",
		HTTPStatusCode: http.StatusBadRequest,
	},
	CodeExpiredPresignedRequest: {
		Code:           "AccessDenied",
		Description:    "Request has expired",
		HTTPStatusCode: http.StatusForbidden,
	},
	CodeInternal: {
		Code:           "InternalError",
		Description:    "We encountered an internal error. Please try again.",
		HTTPStatusCode: http.StatusInternalServerError,
	},
	CodeInvalidAccessKeyID: {
		Code:           "InvalidAccessKeyID",
		Description:    "The access key ID that you provided does not exist in our records.",
		HTTPStatusCode: http.StatusForbidden,
	},
	CodeInvalidContentMD5: {
		Code:           "InvalidDigest",
		Description:    "The Content-MD5 you specified was invalid.",
		HTTPStatusCode: http.StatusBadRequest,
	},
	CodeInvalidContentSHA256: {
		Code:           "InvalidArgument",
		Description:    "x-amz-content-sha256 must be UNSIGNED-PAYLOAD, STREAMING-AWS4-HMAC-SHA256-PAYLOAD, or a valid sha256 value.",
		HTTPStatusCode: http.StatusBadRequest,
	},
	CodeInvalidForceDelete: {
		Code:           "InvalidArgument",
		Description:    "X-Minio-Force-Delete must be a valid boolean.",
		HTTPStatusCode: http.StatusBadRequest,
	},
	CodeInvalidRequest: {
		Code:           "InvalidRequest",
		Description:    "The request is invalid.",
		HTTPStatusCode: http.StatusBadRequest,
	},
	CodeMalformedDate: {
		Code:           "MalformedDate",
		Description:    "Invalid date format header, expected to be in ISO8601, RFC1123 or RFC1123Z time format.",
		HTTPStatusCode: http.StatusBadRequest,
	},
	CodeMalformedExpires: {
		Code:           "AuthorizationQueryParametersError",
		Description:    "X-Amz-Expires should be a number",
		HTTPStatusCode: http.StatusBadRequest,
	},
	CodeMalformedPOSTDate: {
		Code:           "InvalidRequest",
		Description:    "X-Amz-Date must be formatted via ISO8601 Long format.",
		HTTPStatusCode: http.StatusBadRequest,
	},
	CodeMalformedPOSTRequest: {
		Code:           "MalformedPOSTRequest",
		Description:    "The body of your POST request is not well-formed multipart/form-data.",
		HTTPStatusCode: http.StatusBadRequest,
	},
	CodeMalformedPresignedDate: {
		Code:           "MalformedPresignedDate",
		Description:    "X-Amz-Date must be in the ISO8601 Long Format \"yyyyMMdd'T'HHmmss'Z'\"",
		HTTPStatusCode: http.StatusBadRequest,
	},
	CodeMalformedXML: {
		Code:           "MalformedXML",
		Description:    "The XML you provided was not well-formed or did not validate against our published schema.",
		HTTPStatusCode: http.StatusBadRequest,
	},
	CodeMaximumExpires: {
		Code:           "AuthorizationQueryParametersError",
		Description:    "X-Amz-Expires must be less than a week (in seconds); that is, the given X-Amz-Expires must be less than 604800 seconds",
		HTTPStatusCode: http.StatusBadRequest,
	},
	CodeMissingContentLength: {
		Code:           "MissingContentLength",
		Description:    "You must provide the Content-Length HTTP header.",
		HTTPStatusCode: http.StatusLengthRequired,
	},
	CodeMissingPOSTPolicy: {
		Code:           "InvalidArgument",
		Description:    "Bucket POST must contain a field named 'policy'.",
		HTTPStatusCode: http.StatusBadRequest,
	},
	CodeMissingSecurityHeader: {
		Code:           "MissingSecurityHeader",
		Description:    "Your request is missing a required header.",
		HTTPStatusCode: http.StatusBadRequest,
	},
	CodeNegativeExpires: {
		Code:           "AuthorizationQueryParametersError",
		Description:    "X-Amz-Expires must be non-negative",
		HTTPStatusCode: http.StatusBadRequest,
	},
	CodeNoSuchCORSConfiguration: {
		Code:           "NoSuchCORSConfiguration",
		Description:    "The CORS configuration does not exist",
		HTTPStatusCode: http.StatusNotFound,
	},
	CodeNoSuchWebsiteConfiguration: {
		Code:           "NoSuchWebsiteConfiguration",
		Description:    "The specified bucket does not have a website configuration",
		HTTPStatusCode: http.StatusNotFound,
	},
	CodeNotImplemented: {
		Code:           "NotImplemented",
		Description:    "A header that you provided implies functionality that is not implemented.",
		HTTPStatusCode: http.StatusNotImplemented,
	},
	CodeRequestNotReadyYet: {
		Code:           "AccessDenied",
		Description:    "Request is not valid yet",
		HTTPStatusCode: http.StatusForbidden,
	},
	CodeRequestTimeTooSkewed: {
		Code:           "RequestTimeTooSkewed",
		Description:    "The difference between the request time and the server's time is too large.",
		HTTPStatusCode: http.StatusForbidden,
	},
	CodeSignatureDoesNotMatch: {
		Code:           "SignatureDoesNotMatch",
		Description:    "The request signature we calculated does not match the signature you provided. Check your key and signing method.",
		HTTPStatusCode: http.StatusForbidden,
	},
	CodeUnsupportedECDSAP256SHA256: {
		Code:           "NotImplemented",
		Description:    "The AWS4-ECDSA-P256-SHA256 algorithm is not implemented yet.",
		HTTPStatusCode: http.StatusNotImplemented,
	},
	CodeUnsupportedSignature: {
		Code:           "UnsupportedSignature",
		Description:    "The provided request is signed with an unsupported STS Token version or the signature version is not supported.",
		HTTPStatusCode: http.StatusBadRequest,
	},
}
